In [2]:
#pandas sert à manipuler les données.
#train_test_split sert à diviser le dataset en données d’entraînement et données de test. 

import pandas as pd
from sklearn.model_selection import train_test_split

In [4]:
df = pd.read_csv("../data/teleco-churn-clean.csv")

df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,0
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,1
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,0
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,1

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7032 entries, 0 to 7031
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7032 non-null   object
 1   SeniorCitizen     7032 non-null   int64
 2   Partner           7032 non-null   object
 3   Dependents        7032 non-null   object
 4   tenure            7032 non-null   int64
 5   PhoneService      7032 non-null   object
 6   MultipleLines     7032 non-null   object
 7   InternetService   7032 non-null   object
 8   OnlineSecurity    7032 non-null   object
 9   OnlineBackup      7032 non-null   object
 10  DeviceProtection  7032 non-null   object
 11  TechSupport       7032 non-null   object
 12  StreamingTV       7032 non-null   object
 13  StreamingMovies   7032 non-null   object
 14  Contract          7032 non-null   object
 15  PaperlessBilling  7032 non-null   object
 16  PaymentMethod     7032 non-null   object
 17  MonthlyCharges    7032 non-null   float64
 18  TotalCharges      7032 non-null   float64
 19  Churn             7032 non-null   int64
dtypes: float64(2), int64(3), object(15)
memory usage: 1.1+ MB

In [8]:
#En Machine Learning, on sépare toujours :
#X = toutes les colonnes sauf Churn
#y = Churn

X= df.drop("Churn", axis=1)
Y= df["Churn"]

In [10]:
X.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65

In [12]:
Y.head()

0    0
1    0
2    1
3    0
4    1
Name: Churn, dtype: int64

In [14]:
# Cinvertir Catégorie en Numérique : One-Hot Encoding


#pd.get_dummies() transforme les colonnes texte en colonnes numériques.
#drop_first=True supprime une catégorie de référence pour éviter la redondance.
X_encoded = pd.get_dummies(X, drop_first=True)

In [16]:
X_encoded.head()

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,29.85,29.85,False,True,False,False,True,False,...,False,False,False,False,False,False,True,False,True,False
1,0,34,56.95,1889.50,True,False,False,True,False,False,...,False,False,False,False,True,False,False,False,False,True
2,0,2,53.85,108.15,True,False,False,True,False,False,...,False,False,False,False,False,False,True,False,False,True
3,0,45,42.30,1840.75,True,False,False,False,True,False,...,False,False,False,False,True,False,False,False,False,False
4,0,2,70.70,151.65,False,False,False,True,False,False,...,False,False,False,False,False,False,True,False,True,False

In [18]:
X_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7032 entries, 0 to 7031
Data columns (total 30 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   SeniorCitizen                          7032 non-null   int64
 1   tenure                                 7032 non-null   int64
 2   MonthlyCharges                         7032 non-null   float64
 3   TotalCharges                           7032 non-null   float64
 4   gender_Male                            7032 non-null   bool
 5   Partner_Yes                            7032 non-null   bool
 6   Dependents_Yes                         7032 non-null   bool
 7   PhoneService_Yes                       7032 non-null   bool
 8   MultipleLines_No phone service         7032 non-null   bool
 9   MultipleLines_Yes                      7032 non-null   bool
 10  InternetService_Fiber optic            7032 non-null   bool
 11  InternetService_No                     7032 non-null   bool
 12  OnlineSecurity_No internet service     7032 non-null   bool
 13  OnlineSecurity_Yes                     7032 non-null   bool
 14  OnlineBackup_No internet service       7032 non-null   bool
 15  OnlineBackup_Yes                       7032 non-null   bool
 16  DeviceProtection_No internet service   7032 non-null   bool
 17  DeviceProtection_Yes                   7032 non-null   bool
 18  TechSupport_No internet service        7032 non-null   bool
 19  TechSupport_Yes                        7032 non-null   bool
 20  StreamingTV_No internet service        7032 non-null   bool
 21  StreamingTV_Yes                        7032 non-null   bool
 22  StreamingMovies_No internet service    7032 non-null   bool
 23  StreamingMovies_Yes                    7032 non-null   bool
 24  Contract_One year                      7032 non-null   bool
 25  Contract_Two year                      7032 non-null   bool
 26  PaperlessBilling_Yes                   7032 non-null   bool
 27  PaymentMethod_Credit card (automatic)  7032 non-null   bool
 28  PaymentMethod_Electronic check         7032 non-null   bool
 29  PaymentMethod_Mailed check             7032 non-null   bool
dtypes: bool(26), float64(2), int64(2)
memory usage: 398.4 KB

In [21]:
# Diviser En Train Et Test (pour généraliser et non pas mémoriser)
X_train, X_test, y_train, y_test = train_test_split(
    X_encoded,
    Y,
    test_size=0.2, #20% de données pour test
    random_state=42, #Cela rend le résultat reproductible. Si tu relances le code, tu obtiens la même séparation.
    stratify=Y #Très important. Cela garde la même proportion de Churn = 0 et Churn = 1 dans train et test. (bonne pratique)
)

In [23]:
# Vérifier les tailles
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (5625, 30)
X_test: (1407, 30)
y_train: (5625,)
y_test: (1407,)

In [25]:
Y.value_counts(normalize=True) * 100

Churn
0    73.421502
1    26.578498
Name: proportion, dtype: float64

In [26]:
y_train.value_counts(normalize=True) * 100

Churn
0    73.422222
1    26.577778
Name: proportion, dtype: float64

In [27]:
y_test.value_counts(normalize=True) * 100

Churn
0    73.418621
1    26.581379
Name: proportion, dtype: float64

Les porcentages sont très proches grace à stritify

In [28]:
#Sauvegarder les données préparées
X_train.to_csv("../data/X_train.csv", index=False)
X_test.to_csv("../data/X_test.csv", index=False)
y_train.to_csv("../data/y_train.csv", index=False)
y_test.to_csv("../data/y_test.csv", index=False)